spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      format_sql: true
      generate-ddl: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  header: ${JWT_HEADER}
  prefix : ${JWT_PREFIX}
  secret-key: ${JWT_SECRET}
  access-exp: ${TOKEN_EXP}
  refresh-exp: ${REFRESH_EXP}